### ISSUE TITLE
[Feature] Add Achievements

### ISSUE THREAD

**Issue by nathantoannguyen** [nathantoannguyen/KnuckleBones#4]
Create a new module called kb_secret.py for achievements function that handles secret achievements that are difficult to get such as:
- Low Roll: Any board that has all 1s (needs to check if every val in col is filled with 1s)
-  High Roll: Any board that has all 6s (can simply check final score)
- AFK (Can be different Name): Loser's board that has all 0s

**Comment by maithyy** [comment]
should achievements pop up again if the bot board gets an achievement the top board has already gotten? ie: top board gets low roll, should low roll achievement pop up again if the bot board gets low roll or should the achievement only pop up once

**Comment by maithyy** [comment]
also for the low roll achievement do you mean at least one column has all 1's or all 3 columns have all 1's (i think the latter is very impossible though)

same question for the high roll achievement

**Comment by nathantoannguyen** [comment]
Let's say we play a game and I end the game with [[0,0,0],[0,0,0], [0,0,0]]. The game ends normally, saying you won, but the UI should also print something along the lines of "Achievement Unlocked: AFK" and incrementing the number of Achievements, a new row at the bottom for Statistics.

Sure, we can just have it pop up again whenever it happens since it's difficult to get, but only increment number of unique achievements that has already occurred.

It's not impossible to get all 6s, 1s, or 0s on a board, it really depends on how the game is played and what number die is rolled. It'll just be a funny thing to happen and might as well implement it for fun if you have the time.

Note: 
Low Roll: All 1s
AFK/ a different name: All 0s

**Comment by maithyy** [comment]
i finished implementing the achievement system for these achievements but if we were to add achievements that didn't consist of checking the end game full board, I'd have to code 2 different types of achievements

-during game achievements (ie, a col is all 6's)
-end game achievements (the entire board is a certain value)

bc the problem with having it check if an achievement is unlocked after every turn is at the beginning of the game, when the entire board is filled with 0's at the beginning, it counts for the AFK achievement if i put in check achievements after the show game board in the while true loop

i jsut implemented it so that achievements are only checked when the game board is full since thats all the achievements we have so far and tbhhhh i don't think it's worth working too much on now since i think it's better to focus on making this game on different platforms

**Comment by nathantoannguyen** [comment]
@maithyy Yeah no worries, I was working on this slightly too and yeah there would have to be two functions that check the boards in a different way. This is optional anyway so don't feel obligated to do an issue even if I assign you to it.
